In [1]:
import pandas as pd

In [2]:
customers = pd.read_csv("../data/raw/customers.csv")
customers.head()

,customer_id,company_name,signup_date,country,acquisition_channel,company_size_segment,initial_plan,payment_method,is_auto_renew
0,1,"Rodriguez, Figueroa and Sanchez",2023-07-29,United States,organic,medium,Starter,paypal,True
1,2,Doyle Ltd,2023-07-18,United States,organic,small,Starter,credit_card,True
2,3,"Mcclain, Miller and Henderson",2023-07-01,United States,paid_search,small,Starter,credit_card,False
3,4,Davis and Sons,2023-07-04,United States,paid_search,medium,Starter,credit_card,False
4,5,"Guzman, Hoffman and Baldwin",2023-07-18,Germany,partner,small,Starter,paypal,False

In [4]:
subscription_events = pd.read_csv("../data/raw/subscription_events.csv")
subscription_events

,event_id,customer_id,event_date,event_type,plan,previous_plan,mrr_amount,payment_method,is_auto_renew
0,1,1,2023-07-29,new,Starter,NaN,19,paypal,True
1,2,1,2023-08-10,renewal,Starter,NaN,19,paypal,True
2,3,1,2023-09-30,renewal,Starter,NaN,19,paypal,True
3,4,1,2023-10-03,renewal,Starter,NaN,19,paypal,True
4,5,1,2023-11-10,renewal,Starter,NaN,19,paypal,True
...,...,...,...,...,...,...,...,...,...
114157,114158,9386,2026-07-26,new,Starter,NaN,19,credit_card,True
114158,114159,9387,2026-07-11,new,Starter,NaN,19,bank_transfer,False
114159,114160,9388,2026-07-27,new,Growth,NaN,59,paypal,True
114160,114161,9389,2026-07-17,new,Enterprise,NaN,249,paypal,True
114161,114162,9390,2026-07-01,new,Starter,NaN,19,credit_card,True

In [6]:
print(f'Customers columns: {customers.columns}')
print(f'Subscription events columns: {subscription_events.columns}')

Customers columns: Index(['customer_id', 'company_name', 'signup_date', 'country',
       'acquisition_channel', 'company_size_segment', 'initial_plan',
       'payment_method', 'is_auto_renew'],
      dtype='object')
Subscription events columns: Index(['event_id', 'customer_id', 'event_date', 'event_type', 'plan',
       'previous_plan', 'mrr_amount', 'payment_method', 'is_auto_renew'],
      dtype='object')